# Generated by Django 5.0.2 on 2024-02-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('number',)},
        ),
        migrations.RemoveField(
            model_name='solution',
            name='username',
        ),
    ]
